//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel playback of selected sounds.
        /// </summary>
        public static string ActiveSoundContextMenuCommands_AddCommandsToCollection_Cancel_playback_of_selected_sounds {
            get {
                return ResourceManager.GetString("ActiveSoundContextMenuCommands_AddCommandsToCollection_Cancel_playback_of_selecte" +
                        "d_sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new soundboard.
        /// </summary>
        public static string btnAddSoundBoard_ToolTip {
            get {
                return ResourceManager.GetString("btnAddSoundBoard_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sound files to selected soundboard.
        /// </summary>
        public static string btnAddSoundsToSoundBoard_ToolTip {
            get {
                return ResourceManager.GetString("btnAddSoundsToSoundBoard_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected soundboard.
        /// </summary>
        public static string btnRemoveSoundBoard_ToolTip {
            get {
                return ResourceManager.GetString("btnRemoveSoundBoard_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected soundboard.
        /// </summary>
        public static string cbSelectedSoundBoard_ToolTip {
            get {
                return ResourceManager.GetString("cbSelectedSoundBoard_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add soundboard.
        /// </summary>
        public static string CommandsRepository_AddSoundBoard_Add_soundboard {
            get {
                return ResourceManager.GetString("CommandsRepository_AddSoundBoard_Add_soundboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new soundboard.
        /// </summary>
        public static string CommandsRepository_AddSoundBoard_Please_enter_a_name_for_the_new_soundboard {
            get {
                return ResourceManager.GetString("CommandsRepository_AddSoundBoard_Please_enter_a_name_for_the_new_soundboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made to soundboards?.
        /// </summary>
        public static string CommandsRepository_SaveData_Do_you_want_to_save_the_changes_made_to_soundboards_ {
            get {
                return ResourceManager.GetString("CommandsRepository_SaveData_Do_you_want_to_save_the_changes_made_to_soundboards_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save soundboard changes.
        /// </summary>
        public static string CommandsRepository_SaveData_Save_soundboards {
            get {
                return ResourceManager.GetString("CommandsRepository_SaveData_Save_soundboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sounds.
        /// </summary>
        public static string gbActiveSounds_Header {
            get {
                return ResourceManager.GetString("gbActiveSounds_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundboards.
        /// </summary>
        public static string gbSoundBoards_Header {
            get {
                return ResourceManager.GetString("gbSoundBoards_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string gbSounds_Header {
            get {
                return ResourceManager.GetString("gbSounds_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lvActiveSoundsColumnPlaybackPosition_Header {
            get {
                return ResourceManager.GetString("lvActiveSoundsColumnPlaybackPosition_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string lvColumnDelay_Header {
            get {
                return ResourceManager.GetString("lvColumnDelay_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string lvColumnIsLooped_Header {
            get {
                return ResourceManager.GetString("lvColumnIsLooped_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string lvColumnLength_Header {
            get {
                return ResourceManager.GetString("lvColumnLength_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lvColumnName_Header {
            get {
                return ResourceManager.GetString("lvColumnName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string lvColumnVolume_Header {
            get {
                return ResourceManager.GetString("lvColumnVolume_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        public static string MainWindowViewModel_AddSounds__Supported_Files_Separator {
            get {
                return ResourceManager.GetString("MainWindowViewModel_AddSounds__Supported_Files_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose sound files to add.
        /// </summary>
        public static string MainWindowViewModel_AddSounds_Choose_sound_files_to_add {
            get {
                return ResourceManager.GetString("MainWindowViewModel_AddSounds_Choose_sound_files_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File Types.
        /// </summary>
        public static string MainWindowViewModel_AddSounds_Supported_Files {
            get {
                return ResourceManager.GetString("MainWindowViewModel_AddSounds_Supported_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string QuestionDialog_NoButton_Content {
            get {
                return ResourceManager.GetString("QuestionDialog_NoButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string QuestionDialog_YesButton_Content {
            get {
                return ResourceManager.GetString("QuestionDialog_YesButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist: &quot;{0}&quot;.
        /// </summary>
        public static string Sound_ErrorInfo_TheFileDoesNotExist {
            get {
                return ResourceManager.GetString("Sound_ErrorInfo_TheFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected sounds.
        /// </summary>
        public static string SoundContextMenuCommands_AddCommandsToCollection_Remove_selected_sounds {
            get {
                return ResourceManager.GetString("SoundContextMenuCommands_AddCommandsToCollection_Remove_selected_sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename selected sound.
        /// </summary>
        public static string SoundContextMenuCommands_AddCommandsToCollection_Rename_selected_sound {
            get {
                return ResourceManager.GetString("SoundContextMenuCommands_AddCommandsToCollection_Rename_selected_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback of selected sounds.
        /// </summary>
        public static string SoundContextMenuCommands_AddCommandsToCollection_Start_playback_of_selected_sounds {
            get {
                return ResourceManager.GetString("SoundContextMenuCommands_AddCommandsToCollection_Start_playback_of_selected_sound" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name for the sound.
        /// </summary>
        public static string SoundContextMenuCommands_RenameSound_Please_enter_a_new_name_for_the_sound {
            get {
                return ResourceManager.GetString("SoundContextMenuCommands_RenameSound_Please_enter_a_new_name_for_the_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename sound.
        /// </summary>
        public static string SoundContextMenuCommands_RenameSound_Rename_sound {
            get {
                return ResourceManager.GetString("SoundContextMenuCommands_RenameSound_Rename_sound", resourceCulture);
            }
        }
    }
}
